INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Blaise','Pascal','M','1623-06-19','1662-08-19','French','http://history-computer.com/People/images/Blaise_Pascal2.jpg', 'http://en.wikipedia.org/wiki/Blaise_Pascal');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Alan','Turing','M','1912-06-23','1954-06-07','English','http://upload.wikimedia.org/wikipedia/en/c/c8/Alan_Turing_photo.jpg', 'http://en.wikipedia.org/wiki/Alan_Turing');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image) VALUES ('Daniel','Brandur','M','1987-07-23','1987-06-22','Icelandic','https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-xpa1/t31.0-8/10580960_10152319146782087_5075081791575519251_o.jpg');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Charles','Babbage','M','1791-12-26','1871-10-18','English','http://upload.wikimedia.org/wikipedia/commons/6/6b/Charles_Babbage_-_1860.jpg', 'http://en.wikipedia.org/wiki/Charles_Babbage');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Edsger','Djikstra','M','1930-05-11','2002-08-06','Dutch','http://upload.wikimedia.org/wikipedia/commons/d/d9/Edsger_Wybe_Dijkstra.jpg', 'http://en.wikipedia.org/wiki/Edsger_W._Dijkstra');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Chuck','Norris','M','1940-03-10','','American','http://upload.wikimedia.org/wikipedia/commons/3/3e/Chuck_Norris_2007_%28cropped%29.jpg', 'http://en.wikipedia.org/wiki/Chuck_Norris');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Ada','Lovelace','F','1815-12-10','1852-11-27','English','http://upload.wikimedia.org/wikipedia/commons/a/a4/Ada_Lovelace_portrait.jpg', 'http://en.wikipedia.org/wiki/Ada_Lovelace');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Leonhard','Euler','M','1707-04-15','1783-09-18','Swiss','http://upload.wikimedia.org/wikipedia/commons/d/d7/Leonhard_Euler.jpg', 'http://en.wikipedia.org/wiki/Leonhard_Euler');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Donald','Knuth','M','1938-01-10', '','American','http://upload.wikimedia.org/wikipedia/commons/4/4f/KnuthAtOpenContentAlliance.jpg', 'http://en.wikipedia.org/wiki/Donald_Knuth');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Tim','Berners-Lee','M','1955-06-08', '','English','http://upload.wikimedia.org/wikipedia/commons/c/c2/Tim_Berners-Lee_2012.jpg', 'http://en.wikipedia.org/wiki/Tim_Berners-Lee');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Larry','Page','M','1973-03-26', '','American','http://upload.wikimedia.org/wikipedia/commons/2/26/Larry_Page_in_the_European_Parliament%2C_17.06.2009.jpg', 'http://en.wikipedia.org/wiki/Larry_Page');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Sergey','Brin','M','1973-08-21', '','American','http://upload.wikimedia.org/wikipedia/commons/a/a2/Sergey_Brin_cropped.jpg', 'http://en.wikipedia.org/wiki/Sergey_Brin');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Steve','Wozniak','M','1950-08-11', '','American','http://upload.wikimedia.org/wikipedia/commons/f/f6/Steve_Wozniak.jpg', 'http://en.wikipedia.org/wiki/Steve_Wozniak');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('John','Backus','M','1924-12-03', '2007-03-17','American','http://www.computerhistory.org/fellowawards/media/img/fellows/1997_john_backus.jpg', 'http://en.wikipedia.org/wiki/John_Backus');
INSERT INTO scientists(first_name, last_name, gender, birth_date, death_date, nationality, image, wiki) VALUES ('Tony','Hoare','M','1934-01-11', '','British','http://upload.wikimedia.org/wikipedia/commons/2/2c/Sir_Tony_Hoare_IMG_5125.jpg', 'http://en.wikipedia.org/wiki/Tony_Hoare');

INSERT INTO types(type) VALUES ('Mechanical');
INSERT INTO types(type) VALUES ('Electronic');
INSERT INTO types(type) VALUES ('Transistor');

INSERT INTO computers(name, build_year, type_id, built, image, wiki) VALUES ('Pascaline',1642, 1,1, 'http://i2.cdn.turner.com/cnn/dam/assets/130522140807-the-pascaline-mechanical-calculator-horizontal-gallery.jpg', 'http://en.wikipedia.org/wiki/Pascal%27s_calculator');
INSERT INTO computers(name, build_year, type_id, built, image, wiki) VALUES ('ABC',1942, 2,1, 'http://www.askthecomputertech.com/images/abc-computer.jpg', 'http://en.wikipedia.org/wiki/Atanasoff%E2%80%93Berry_computer');
INSERT INTO computers(name, build_year, type_id, built, image, wiki) VALUES ('Colossus',1943, 2,1, 'http://upload.wikimedia.org/wikipedia/commons/4/4b/Colossus.jpg', 'http://en.wikipedia.org/wiki/Colossus_computer');
INSERT INTO computers(name, build_year, type_id, built, image, wiki) VALUES ('Difference Engine',1822, 1,1, 'http://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Babbage_Difference_Engine.jpg/640px-Babbage_Difference_Engine.jpg', 'http://en.wikipedia.org/wiki/Difference_engine');
INSERT INTO computers(name, build_year, type_id, built, image, wiki) VALUES ('Analytical Engine',1837, 1,1, 'http://www.chronarion.org/ada/AnalyticalEngine.jpg', 'http://en.wikipedia.org/wiki/Analytical_Engine');
INSERT INTO computers(name, build_year, type_id, built, image, wiki) VALUES ('Apple 1',1976, 2,1, 'http://www.computersciencelab.com/ComputerHistory/HtmlHelp/Images2/Apple1.jpg', 'http://en.wikipedia.org/wiki/Apple_I');
INSERT INTO computers(name, build_year, type_id, built, image, wiki) VALUES ('ENIAC',1946, 2,1, 'http://www.library.upenn.edu/exhibits/rbm/mauchly/img/eniac3.jpg', 'http://en.wikipedia.org/wiki/ENIAC');

INSERT INTO scientist_computer(scientist_id, computer_id) VALUES (1, 1);
INSERT INTO scientist_computer(scientist_id, computer_id) VALUES (4, 4);
INSERT INTO scientist_computer(scientist_id, computer_id) VALUES (4, 5);
INSERT INTO scientist_computer(scientist_id, computer_id) VALUES (13, 6);
